# Generated by Django 5.2.8 on 2025-11-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=255, unique='title')),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('release_date', models.DateField()),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('language', models.CharField(default='English', max_length=50)),
                ('age_rating', models.CharField(choices=[('G', 'General'), ('PG', 'Parental Guidance'), ('PG-13', 'PG-13'), ('R', 'Restricted'), ('18+', 'Adults Only')], default='PG', max_length=10)),
                ('status', models.CharField(choices=[('now_showing', 'Now Showing'), ('coming_soon', 'Coming Soon'), ('archived', 'Archived')], default='coming_soon', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genre', models.ManyToManyField(related_name='movies', to='movie.genre')),
            ],
            options={
                'verbose_name_plural': 'Movies',
                'ordering': ['-created_at'],
            },
        ),
    ]
